New alert that is triggered if an instance of GLBC is down
kcp-dev/kcp-glbc pull request #429
Opened 2022-09-30 08:50 UTC by ChristianZaccaria

Closes #393

## Description of Changes
- This alert checks for specific labels that are absent such as "kcp-stable-redhat-hcg". If a label is absent, alert is triggered and will display which GLBC instance is/are down.
- I created a unit test to test for 3 possible scenarios: 1 GLBC instance being down, or 2 or 3 GLBC instances being down at the same time.
- Created directory to store unit tests for alerts specific to Openshift. For this reason, I also added extra commands in the prometheus-rules-unit-test make target to perform tests from the Openshift dir.

2022-09-30 09:41 UTC, david-martin requested changes
This will help a lot. 👍 
1 suggestion to change the sev to critical so we get notified

2022-09-30 09:41 UTC, david-martin commented on config/observability/monitoring_resources/openshift/GLBCInstanceDown.dhall
> +        (toMap { severity = AlertSeverity.show AlertSeverity.Type.Warning })
```suggestion
        (toMap { severity = AlertSeverity.show AlertSeverity.Type.Critical })
```

2022-10-03 08:12 UTC, ChristianZaccaria commented on config/observability/monitoring_resources/openshift/GLBCInstanceDown.dhall
> +        (toMap { severity = AlertSeverity.show AlertSeverity.Type.Warning })
Excellent, thanks @david-martin . I just changed that to critical now and ran `make gen-monitoring-resources`, and changed the severity in unit tests. :+1:

2022-10-03 08:29 UTC, david-martin approved these changes

2022-10-03 08:29 UTC, merged