Hash Domain Verification Token value + Unit Test
kcp-dev/kcp-glbc pull request #474
Opened 2022-10-18 14:56 UTC by ChristianZaccaria

Closes #447 

## Description of Changes
- Added two functions containing an algorithm to hash the domain verification token. (Same ones used by `kcp`)
- Updated the GetToken() function to return a hashed value of the domain verification token.
- Created a unit test for this function.
- Updated tests to not expect a workspace value.

2022-10-18 15:46 UTC, david-martin requested changes

2022-10-18 15:46 UTC, david-martin commented on pkg/apis/kuadrant/v1/types.go
> +	return fmt.Sprintf("%s", workloadv1alpha1.ToSyncTargetKey(logicalcluster.From(in), ""))
why import workloadv1alpha1 and also copy the impl of ToSyncTargetKey into this file?

2022-10-18 15:46 UTC, david-martin commented on pkg/apis/kuadrant/v1/types.go
> +func ToSyncTargetKey(syncTargetWorkspace logicalcluster.Name, syncTargetName string) string {
The hashing function is probably fine.
The name is a little odd in the context of a DomainVerification.
Can it just be a generic function for hashing a string? It doesn't have to match the synctarget key.

2022-10-18 15:46 UTC, david-martin commented on pkg/apis/kuadrant/v1/types.go
> +func ToSyncTargetKey(syncTargetWorkspace logicalcluster.Name, syncTargetName string) string {
Could just be something like https://gobyexample.com/sha256-hashes

2022-10-18 16:41 UTC, ChristianZaccaria commented on pkg/apis/kuadrant/v1/types.go
> +	return fmt.Sprintf("%s", workloadv1alpha1.ToSyncTargetKey(logicalcluster.From(in), ""))
You're right. I'm wondering, since the hash function will be a generic one, should I place these functions somewhere else? Perhaps under [util](https://github.com/kcp-dev/kcp-glbc/tree/main/pkg/_internal/util).

2022-10-24 11:08 UTC, maleck13 commented on pkg/apis/kuadrant/v1/types_test.go
> +				if !reflect.DeepEqual(obj.GetToken(), expectedToken) {
as this is just a string, I think we can just use string comparison

2022-10-24 11:08 UTC, maleck13 reviewed
minor changes

2022-10-24 15:31 UTC, ChristianZaccaria commented on pkg/apis/kuadrant/v1/types_test.go
> +				if !reflect.DeepEqual(obj.GetToken(), expectedToken) {
I tried: `if obj.GetToken() == expectedToken {` but the test would fail eventhough the expected value is the same. I think it's because the GetToken() function makes use of the [DomainVerification struct pointer](https://github.com/kcp-dev/kcp-glbc/blob/080e0f226d8e84f1efad9ab61c72009c831ccd70/pkg/apis/kuadrant/v1/types.go#L28). What do you think?

2022-10-24 15:44 UTC, ChristianZaccaria commented on pkg/apis/kuadrant/v1/types_test.go
> +				if !reflect.DeepEqual(obj.GetToken(), expectedToken) {
You're right, I added that just now

2022-10-24 15:46 UTC, ChristianZaccaria commented on pkg/_internal/util/math/hash_test.go
> +package math
Do you mean in its own math_testing directory? Should I also include the slice_test.go one in it?

2022-10-26 07:29 UTC, maleck13 commented on pkg/_internal/util/math/hash_test.go
> +package math
No. In go tests for a package name can be named `_testing which means you can have it in the same directory but it only has access to the exported API

2022-10-26 12:36 UTC, maleck13 commented on pkg/apis/kuadrant/v1/types_test.go
> +				if !reflect.DeepEqual(obj.GetToken(), expectedToken) {
ok so you have changed it to be ``` object.GetToken() != expectedToken```?

2022-10-27 14:31 UTC, ChristianZaccaria commented on pkg/apis/kuadrant/v1/types_test.go
> +				if !reflect.DeepEqual(obj.GetToken(), expectedToken) {
Yes exactly, changes have been pushed now, thanks @maleck13  :+1:

2022-10-28 12:28 UTC, maleck13 approved these changes

2022-11-02 08:57 UTC, david-martin approved these changes

2022-11-02 08:57 UTC, david-martin commented
Thanks @ChristianZaccaria

2022-11-02 08:57 UTC, merged